
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[prune]
  go-tests = true
  unused-packages = true
